### ISSUE TITLE
Getting timeouts for rabbitmq heatbeat

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/func_adl_server#13]
Not sure exactly what caused this, but we are seeing this with some frequency. It could be due to a laptop sleeping, etc. Need to track it.

```
PS C:\Users\gordo\Documents\Code\IRIS-HEP\func_adl_server> kubectl logs --previous lovely-skunk-status-596c6c97d8-kf9qn                                                                          Traceback (most recent call last):                                                                                                                                                                 File "state_updater.py", line 90, in <module>
    listen_to_queue (sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "state_updater.py", line 83, in listen_to_queue
    channel.start_consuming()
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1857, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2018, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 826, in process_data_events
    self._flush_output(common_terminator)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.AMQPHeartbeatTimeout: No activity or too many missed heartbeats in the last 60 seconds
```

**Comment by abdelrahman-a-ibrahim** [comment]
@andresbono
I am getting the same issue now with bitnami chart version: 10.3.5
Do you have any advice on that, please?

**Comment by andresbono** [comment]
Hi @abdelrhman1410, if you think there is some problem with a Bitnami chart, please open an issue in https://github.com/bitnami/charts and the team will check it. Thanks!!
